"dialect:ansi":
  - "/(ansi)/i"

"dialect:athena":
  - "/(athena)/i"

"dialect:bigquery":
  - "/(bigquery)/i"

"dialect:clickhouse":
  - "/(clickhouse)/i"

"dialect:databricks":
  - "/(databricks)/i"

"dialect:db2":
  - "/(db2)/i"

"dialect:doris":
  - "/(doris)/i"

"dialect:duckdb":
  - "/(duckdb)/i"

"dialect:exasol":
  - "/(exasol)/i"

"dialect:flink":
  - "/(flink)/i"

"dialect:greenplum":
  - "/(greenplum)/i"

"dialect:hive":
  - "/(hive)/i"

"dialect:impala":
  - "/(impala)/i"

"dialect:mariadb":
  - "/(mariadb)/i"

"dialect:materialize":
  - "/(materialize)/i"

"dialect:mysql":
  - "/(mysql)/i"

"dialect:oracle":
  - "/(oracle)/i"

"dialect:postgres":
  - "/(postgres)/i"

"dialect:redshift":
  - "/(redshift)/i"

"dialect:snowflake":
  - "/(snowflake)/i"

"dialect:soql":
  - "/(soql)/i"

"dialect:sparksql":
  - "/(sparksql)/i"

"dialect:sqlite":
  - "/(sqlite)/i"

"dialect:starrocks":
  - "/(starrocks)/i"

"dialect:t-sql":
  - "/(t-sql|tsql)/i"

"dialect:teradata":
  - "/(teradata)/i"

"dialect:trino":
  - "/(trino)/i"

"dialect:vertica":
  - "/(vertica)/i"
